### PR TITLE
Update to ES6

### PR DESCRIPTION
**Pull request by chensokheng123**
What do you think?

### CODE REVIEW

**Comment by surasnayak** [comment]
@Chensokheng  Looks good, can you put a GIF of the game to make sure that it is still working with the changes. If everything looks fine I will go ahead and merge it.

**Comment by chensokheng123** [comment]
Can you be more specific? I don't understand what you mean?

**Comment by surasnayak** [comment]
I need to be sure that the game is still working with your updates. So I need you to run the game which has the updates you have done from your local computer and as a proof do screen recording and upload it here.

P.S : You cannot upload videos to comment section so you need to convert it to GIF and upload it here.

**Comment by chensokheng123** [comment]
you can check on this link  https://gph.is/g/amn1AXZ

**Comment by surasnayak** [comment]
@Chensokheng great work. I would really like you to checkout my other issues and repos. :-)

**Pull request merged**
